# Generated by Django 2.2.7 on 2021-10-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientC2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='past_clients')),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ClientC3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='past_clients')),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ClientC4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='past_clients')),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ClientC5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='past_clients')),
                ('link', models.URLField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Client',
            new_name='ClientC1',
        ),
    ]
