# Generated by Django 2.2.7 on 2021-10-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211017_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientc1',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientc2',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientc3',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientc4',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientc5',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
