# Generated by Django 2.2.7 on 2021-10-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('link', models.URLField()),
                ('software1', models.ImageField(blank=True, null=True, upload_to='software')),
                ('software2', models.ImageField(blank=True, null=True, upload_to='software')),
                ('software3', models.ImageField(blank=True, null=True, upload_to='software')),
                ('s1_name', models.CharField(max_length=300)),
                ('s2_name', models.CharField(max_length=300)),
                ('s3_name', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='project_image')),
            ],
        ),
    ]
