# Generated by Django 2.2.7 on 2021-10-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20211017_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='software1',
            field=models.FileField(blank=True, null=True, upload_to='software'),
        ),
        migrations.AlterField(
            model_name='project',
            name='software2',
            field=models.FileField(blank=True, null=True, upload_to='software'),
        ),
        migrations.AlterField(
            model_name='project',
            name='software3',
            field=models.FileField(blank=True, null=True, upload_to='software'),
        ),
    ]
